Manish_L/Manish/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

Manish_L/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^welcome/$', views.welcome, name='welcome'),

    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    
  #  url(r'^register$', views.UserFormView.as_view(), name='register'),
    
    url(r'^wish$', views.create_wish, name='create_wish'),
    
    url(r'^image$', views.create_image, name='create_image'),
    
    url(r'^image_url$', views.create_image_url, name='create_image_url'),
    ]

Manish_L/home/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse

class Wish(models.Model):
    
    user = models.ForeignKey(User, default=1)
    wish_text = models.CharField(max_length = 75)
        
    def get_absolute_url(self):
        return reverse('home:home')
    
    def __str__(self):
        return self.wish_text

class Image(models.Model):
    
    user = models.ForeignKey(User, default=1)
    wish_image = models.FileField(null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse('home:home')
    
    
class Image_url(models.Model):
    
    user = models.ForeignKey(User, default=1)
    name = models.CharField(max_length = 100)
    image_url =  models.CharField(max_length = 500)
    
    def get_absolute_url(self):
        return reverse('home:home')

    def __str__(self):
        return self.name

Manish_L/home/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Wish,Image,Image_url

class WishForm(forms.ModelForm):

    class Meta:
        model = Wish
        fields = ['wish_text']
        
class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ['wish_image']

class ImageUrlForm(forms.ModelForm):

    class Meta:
        model = Image_url
        fields = ['name', 'image_url']


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Manish_L/home/views.py
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.db.models import Q
from django.views.generic import View
from django.views.generic.edit import CreateView
from .models import Wish, Image, Image_url
from .forms import UserForm,WishForm,ImageForm,ImageUrlForm

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def welcome(request):
    
    return render(request, 'home/welcome.html')


def create_wish(request):
    if not request.user.is_authenticated():
        return render(request, 'home/login.html')
    else:
        form = WishForm(request.POST or None)
        if form.is_valid():
            wish = form.save(commit=False)
            wish.user = request.user
            wish.save()
            
            all_wish = Wish.objects.filter(user=request.user)
            all_image = Image.objects.filter(user=request.user)
            all_image_url = Image_url.objects.filter(user=request.user)
            return render(request, 'home/home.html', {'all_wish' : all_wish, 'all_image' : all_image, 'all_image_url':all_image_url})
            #return render(request, 'home/home.html', {'wish': wish})
        context = {
            "form": form,
        }
        return render(request, 'home/create_wish.html', context)




def create_image(request):
    if not request.user.is_authenticated():
        return render(request, 'home/login.html')
    else:
        form = ImageForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.wish_image = request.FILES['wish_image']
            file_type = image.wish_image.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'image': image,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'home/create_image.html', context)
            image.save()
            
            all_wish = Wish.objects.filter(user=request.user)
            all_image = Image.objects.filter(user=request.user)
            all_image_url = Image_url.objects.filter(user=request.user)
            return render(request, 'home/home.html', {'all_wish' : all_wish, 'all_image' : all_image, 'all_image_url':all_image_url})
            #return render(request, 'home/home.html', {'image': image})
        context = {
            "form": form,
        }
        return render(request, 'home/create_image.html', context)
    
    
def create_image_url(request):
    if not request.user.is_authenticated():
        return render(request, 'home/login.html')
    else:
        form = ImageUrlForm(request.POST or None)
        if form.is_valid():
            image_url = form.save(commit=False)
            image_url.user = request.user
            image_url.save()
            all_wish = Wish.objects.filter(user=request.user)
            all_image = Image.objects.filter(user=request.user)
            all_image_url = Image_url.objects.filter(user=request.user)
            return render(request, 'home/home.html', {'all_wish' : all_wish, 'all_image' : all_image, 'all_image_url':all_image_url})
            #return render(request, 'home/home.html', {'image_url': image_url})
        context = {
            "form": form,
        }
        return render(request, 'home/create_image_url.html', context)


def home(request):
    
    if not request.user.is_authenticated():
        return render(request, 'home/welcome.html')
    else:
        user = request.user
        all_wish = Wish.objects.filter(user=request.user)
        all_image = Image.objects.filter(user=request.user)
        all_image_url = Image_url.objects.filter(user=request.user)
        return render(request, 'home/home.html', {'user': user, 'all_wish' : all_wish, 'all_image' : all_image, 'all_image_url':all_image_url})
   # return render(request, 'home/index.html')


#def wish(request):
    
#    return render(request, 'home/enter_wish.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'home/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_wish = Wish.objects.filter(user=request.user)
                all_image = Image.objects.filter(user=request.user)
                all_image_url = Image_url.objects.filter(user=request.user)
                return render(request, 'home/home.html', {'all_wish' : all_wish, 'all_image' : all_image, 'all_image_url':all_image_url})
            else:
                return render(request, 'home/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'home/login.html', {'error_message': 'Invalid login'})
    return render(request, 'home/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_wish = Wish.objects.filter(user=request.user)
                all_image = Image.objects.filter(user=request.user)
                all_image_url = Image_url.objects.filter(user=request.user)
                return render(request, 'home/home.html', {'all_wish' : all_wish, 'all_image' : all_image, 'all_image_url':all_image_url})
    context = {
        "form": form,
    }
    return render(request, 'home/register.html', context)


#===============================================================================
# class UserFormView(View):
#     form_class = UserForm
#     template_name = 'home/registration_form.html'
#     
#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {'form': form})
#         
#     def post(self, request):
#         form = self.form_class(request.POST)
#         
#         if form.is_valid():
#             user = form.save(commit=False)
#             
#             
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user.set_password(password)
#             user.save()
#         
#             user = authenticate(username=username, password=password)
#         
#             if user is not None:
#             
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('home:home')
#             
#         return render(request, self.template_name, {'form': form})
#===============================================================================

Manish_L/home/templates/home/create_image.html
{% extends 'home/main_template.html' %}

{% block body %}

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
	{% include 'home/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
	</div>
		
</form>


{% endblock %}

Manish_L/home/templates/home/create_image_url.html
{% extends 'home/main_template.html' %}

{% block body %}

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
	{% include 'home/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
	</div>
		
</form>

{% endblock %}

Manish_L/home/templates/home/create_wish.html
{% extends 'home/main_template.html' %}

{% block body %}

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
	{% include 'home/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-12" style="text-align: center;">
		<button type="submit" class="btn" style="color: black; background-color: yellow "><b>Submit</b></button>
		</div>
		
</form>

{% endblock %}

Manish_L/home/templates/home/form-template.html
{% for field in form %}

	<div class="form-group">
		<div class="col-sm-offset-4 col-sm-8">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<div class="col-md-12" style="text-align: center;">
			
			<label style="color: yellow;"><h4><b>{{ field.label_tag }}</b><h4></label>&nbsp;&nbsp;&nbsp;
			<div class="col-md-12" style="text-align: center; color: black">{{field}}</div>
		</div>
	</div>	
			
{% endfor %}

Manish_L/home/templates/home/home.html
{% extends 'home/main_template.html' %}

{% block body %}

<div class="col-sm-10" style="visibility: Hidden">
{% for images in all_image %}
	
    		<img id="img{{ forloop.counter }}" src="{{images.wish_image.url}}" height="20"/>

{% endfor %}

{% for images_url in all_image_url %}
	
    		<img id="imga{{ forloop.counter }}" src="{{images_url.image_url}}" height="20"/>

{% endfor %}


</div>


{% for wishes in all_wish %}

	<div class="col-md-12" style="text-align: center; color: yellow">
		<h2><i><b>{{wishes}}</b></i></h2>
		</div>

{% endfor %}

{% for images in all_image %}
		
{% endfor %}

{% for images_url in all_image_url %}
		
{% endfor %}

{% endblock %}

Manish_L/home/templates/home/login.html
{% extends 'home/visitor_template.html' %}

{% block body %}

<div class="outer">
<div class="middle">
<div class="inner">

<div class="container-fluid">
	
	<div class="row">
  				<div class="col-md-2"></div>
  				<div class="col-md-8">
    			<h2 style="bold: true; background-color: transparent; color:white; font-size:450%; text-align:center">
       				<span style=" font-size:150%; font-family: 'Cookie', cursive; color: yellow " ><i><b>i</b></i></span>
       				<span style="font-family: 'Indie Flower', cursive">&nbsp;Wish Here</span>
       			</h2>
       			</div>
    			<div class="col-md-2"></div>
 	</div>
 	
    <div class="row">
    <div class="col-md-12">
         <div class="col-md-4"></div>
         	<div class="col-md-4">
            	<div class="panel panel-default" style="background: transparent; border: none !important;">
                	<div class="panel-body" >
                    	{% if error_message %}
                        	<p style="color: white"><strong>{{ error_message }}</strong></p>
                    	{% endif %}
                    	<form class="form-horizontal"  role="form" action="{% url 'home:login_user'%}" method="post" enctype="multipart/form-data">
                        	{% csrf_token %}
                        	<div class="form-group" >
                            	
                            	<div class="col-md-12" style="text-align: center;">
                                	<input id="id_username" placeholder="Username" maxlength="30" name="username" type="text">
                            	</div>
                        	</div>
                        	<div class="form-group">
                            	
                            	<div class="col-md-12" style="text-align: center;">
                                	<input id="id_password" placeholder="Password" maxlength="30" name="password" type="password">
                            	</div>
                        	</div>
                        	<div class="form-group">
                            	<div class="col-md-12" style="text-align: center;">
                                	<button type="submit" class="btn">Login</button>
                                	<a href="{% url 'home:register' %}">
      									<input type="button" value="New User" class="btn" style="color : black"></input>
      								</a>
                            	</div>
                            
                            	
                        	</div>
                    	</form>
                	</div>
                	
				</div>
        	</div>
     	</div>
     	</div>
     	
    </div>
 
  
 




 </div>
 </div>
 </div>

{% endblock %}

Manish_L/home/templates/home/main_template.html
<!DOCTYPE html>
<html>
<head>
<title>i Wish Here</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico">
<link href="https://fonts.googleapis.com/css?family=Cookie|Indie+Flower" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap&callback=initMap"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<style>
            body {
                background: black;
               
            }
            
            #myCanvas {
    			padding: 0;
    			margin: auto;
    			margin-top: 2cm;
    			margin-bottom: 2cm;
   				display: block;
    			width: 1250px;
    			height: 2000px;
   				top: 0;
    			bottom: 0;
    			left: 0;
    			right: 0;
    			border:5px solid #FFFFFF;
    			background:#FFFFFF;
    			
			}
			
			.wrapper {
    			text-align: center;
    			margin-top: 1cm;
			}

			.button {
    			position: absolute;
    			
    		}
    		
    		.navbar {
    			border-radius: 0;
    		}
    		
    		.navbar-brand {
   				font-family: 'Pacifico', cursive;
   			}
</style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        
	<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:home'%}" style="font-size: 120%"">
       				<span style=" font-size:250%; font-family: 'Cookie', cursive; color: yellow " ><i><b>i</b></i></span>
       				<span style="font-size:150%;font-family: 'Indie Flower', cursive; color: white">&nbsp;<b>Wish Here</b></span>
			</a>
        </div>

	
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
           
        	<!-- 
           <ul class="nav navbar-nav navbar-left">
            
              <li class="">
		<a href="#">
		
			<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
			<span><i class="fa fa-facebook-square" style="font-size:24px;color:#c2c0c0"></i></span>
		</a>
		</li>
		
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-twitter-square' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-instagram' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		</li>
         
        </ul> 
        
        -->
           
            <ul class="nav navbar-nav navbar-right">
            
         
                <li>
                    <a href="{% url 'home:create_wish' %}" style="color: white">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true" style="color: white"></span>&nbsp; 
					Add Wish
                    </a>
                </li>
                <li>
                    <a href="#" style="color: white">
                    <!--{% url 'home:create_image' %}, {% url 'home:create_image_url' %} -->
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true" style="color: white"></span>&nbsp; 
			Options
                    </a>
                </li>
                <li>
                    <a href="#" style="color: white">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true" style="color: white"></span>&nbsp; 
                        Sahil Kalra
                    </a>
                </li>
                
                <li>
                    <a href="{% url 'home:logout_user' %}" style="color: white">
                        <span class="glyphicon glyphicon-off" aria-hidden="true" style="color: white"></span>&nbsp; Logout
                    </a>
                </li>
                

            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

Manish_L/home/templates/home/register.html
{% extends 'home/visitor_template.html' %}

{% block body %}
<div class="outer">
<div class="middle">
<div class="inner">

<div class="container-fluid">


	<div class="row">
  				<div class="col-md-2"></div>
  				<div class="col-md-8">
    			<h2 style="bold: true; background-color: transparent; color:white; font-size:450%; text-align:center;=">
       				<span style=" font-size:150%; font-family: 'Cookie', cursive; color: yellow " ><i><b>i</b></i></span>
       				<span style="font-family: 'Indie Flower', cursive">&nbsp;Wish Here</span>
       			</h2>
       			</div>
    			<div class="col-md-2"></div>
 	</div>

    <div class="row">
    <div class="col-md-12">
         <div class="col-md-4"></div>
         	<div class="col-md-4">
            	<div class="panel panel-default" style="background: transparent; border: none !important;">
                	<div class="panel-body" style="text-align: center;">
                    	{% if error_message %}
                        	<p style="color: white"><strong>{{ error_message }}</strong></p>
                    	{% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form-template.html' %}
                        <div class="form-group">
                            <div class="col-md-12" style="text-align: center;">
                                <button type="submit" class="btn">Register</button>
                                <a href="{% url 'home:login_user' %}">
      							<input type="button" value="Login" class="btn" style="color : black"></input>
      							</a>
                            </div>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>
    </div>


 </div>
 </div>
 </div>
 </div>
{% endblock %}

Manish_L/home/templates/home/visitor_template.html
<!DOCTYPE html>
<html>
<head>
<title>i Wish Here</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico">
<link href="https://fonts.googleapis.com/css?family=Cookie|Indie+Flower" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap&callback=initMap"></script>


<style>
            body{
	background: white url("/media/background.jpg") no-repeat center center fixed;
	-webkit-background-size: cover;
  	-moz-background-size: cover;
  	-o-background-size: cover;
  	background-size: cover;
}
            #myCanvas {
    			padding: 0;
    			margin: auto;
    			margin-top: 2cm;
    			margin-bottom: 2cm;
   				display: block;
    			width: 1250px;
    			height: 2000px;
   				top: 0;
    			bottom: 0;
    			left: 0;
    			right: 0;
    			background:#FFFFFF;
			}
		
			.wrapper {
    			text-align: center;
    			margin-top: 1cm;
			}

			.button {
    			position: absolute;
    			
    		}
    		
    		.navbar {
    			border-radius: 0;
    		}
    		
    		.navbar-brand {
   				font-family: 'Pacifico', cursive;
   			}
   			
   			 .outer {
    display: table;
    position: absolute;
    height: 100%;
    width: 100%;
}

.middle {
    display: table-cell;
    vertical-align: middle;
}

.inner {
    margin-left: auto;
    margin-right: auto; 
    width: 100%
}	
</style>

</head>
<body>

{% block body %}
{% endblock %}
</body>
</html>

Manish_L/home/templates/home/welcome.html
<!DOCTYPE html>
<html>
<head>
<title>i Wish Here</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico">
<link href="https://fonts.googleapis.com/css?family=Cookie|Indie+Flower" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap&callback=initMap"></script>
<style>
   	
   	.outer {
    display: table;
    position: absolute;
    height: 100%;
    width: 100%;
}

.middle {
    display: table-cell;
    vertical-align: middle;
}

.inner {
    margin-left: auto;
    margin-right: auto; 
    width: 100%
}

body{
	background: white url("/media/background.jpg") no-repeat center center fixed;
	-webkit-background-size: cover;
  	-moz-background-size: cover;
  	-o-background-size: cover;
  	background-size: cover;
}

.col-md-2 a:hover{

text-decoration: None;

}
</style>
</head>


<body>
<div class="outer">
  <div class="middle">
  <div class="inner">

<div class="row">
  				<div class="col-md-2"></div>
  				<div class="col-md-8">
    			<h2 style="bold: true; background-color: transparent; color:white; font-size:450%; text-align:center;"">
       				<span style=" font-size:150%; font-family: 'Cookie', cursive; color: yellow " ><i><b>i</b></i></span>
       				<span style="font-family: 'Indie Flower', cursive">&nbsp;Wish Here</span>
       			</h2>
       			</div>
    			<div class="col-md-2"></div>
 </div>
 
 <div class="row" style="height:20px;"></div>
 
 <div class="row">
 <div class="col-md-5"></div>
  <div class="col-md-1">
      <a href="{% url 'home:login_user' %}">
      	<h2 style="font-family: 'Cookie', cursive; background-color: transparent; color:white; font-size:200%; text-align:center;">Login</h2>
      </a>
  </div>
  
  <div class="col-md-1">
  
      <a href="{% url 'home:register' %}">
      	<h2 style="font-family: 'Cookie', cursive; background-color: transparent; color:white; font-size:200%; text-align:center;">Register</h2>
      </a>
   <div class="col-md-5"></div>
  </div>
  
 </div>
 
 </div>
 </div>
 </div>

</body>
</html>