Manish/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^wish$', views.wish.as_view(), name='wish'),
    
    url(r'^image$', views.image.as_view(), name='image'),
    
    url(r'^image_url$', views.image_url.as_view(), name='image_url'),
    ]

Manish/home/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Wish(models.Model):

    wish_text = models.CharField(max_length = 75)
        
    def get_absolute_url(self):
        return reverse('home:home')
    
    def __str__(self):
        return self.wish_text

class Image(models.Model):

    wish_image = models.FileField(null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse('home:home')
    
    
class Image_url(models.Model):
    
    name = models.CharField(max_length = 100)
    image_url =  models.CharField(max_length = 500)
    
    def get_absolute_url(self):
        return reverse('home:home')

    def __str__(self):
        return self.name

Manish/home/views.py
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.views.generic.edit import CreateView
from .models import Wish, Image, Image_url


def home(request):
    all_wish = Wish.objects.all()
    all_image = Image.objects.all()
    all_image_url = Image_url.objects.all()
    return render(request, 'home/home.html', {'all_wish' : all_wish, 'all_image' : all_image, 'all_image_url':all_image_url})
   # return render(request, 'home/index.html')


#def wish(request):
    
#    return render(request, 'home/enter_wish.html')

class wish(CreateView):
    model = Wish
    fields = ['wish_text']
    
class image(CreateView):
    model = Image
    fields = ['wish_image']
    
class image_url(CreateView):
    model = Image_url
    fields = ['name','image_url']

Manish/home/templates/home/home.html
<!DOCTYPE html>
<html>
<head>
<title>Hunger Theka</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap&callback=initMap"></script>



<style>
            body {
                background: #b8c6d0;
               
            }
            
            #myCanvas {
    			padding: 0;
    			margin: auto;
    			margin-top: 2cm;
    			margin-bottom: 2cm;
   				display: block;
    			width: 1250px;
    			height: 2000px;
   				top: 0;
    			bottom: 0;
    			left: 0;
    			right: 0;
    			background:#aaaaaa;
			}
			
			.wrapper {
    			text-align: center;
    			margin-top: 1cm;
			}

			.button {
    			position: absolute;
    			
    		}
        
</style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        
	<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:home'%}" style="font-size: 170%"">M K</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
           
           <ul class="nav navbar-nav navbar-left">
            
              <li class="">
		<a href="#">
		
			<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<i class="fa fa-facebook-square" style="font-size:24px;color:#c2c0c0"></i></span>
		</a>
		</li>
		
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-twitter-square' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-instagram' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		</li>
         
        </ul> 
           
            <ul class="nav navbar-nav navbar-right">
            
         
            <li class="">
		<a href="#">
		
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>&nbsp; 
			Doodle</a>
		</li>
            	<li class="">
		<a href="#">
			<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp;
			 Find Us</a>
		</li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 
			About Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp; 
			Contact Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; 
                        Developed by Sahil Kalra
                    </a>
                </li>
                

            </ul>
        </div>

    </div>
</nav>

<div class="wrapper">
<a href=" {% url 'home:wish' %} "><button type="button" class="btn btn-primary">Wish text</button></a>
<a href=" {% url 'home:image' %} "><button type="button" class="btn btn-primary">Wish Image</button></a>
<a href=" {% url 'home:image_url' %} "><button type="button" class="btn btn-primary">Wish Image Url</button></a>
</div>


<div class="col-sm-10" style="visibility: Hidden">
{% for images in all_image %}
	
    		<img id="img{{ forloop.counter }}" src="{{images.wish_image.url}}" height="20"/>

{% endfor %}

{% for images_url in all_image_url %}
	
    		<img id="imga{{ forloop.counter }}" src="{{images_url.image_url}}"/>

{% endfor %}


</div>

<canvas id="myCanvas" width="1250" height="2000"
style="border:3px solid #d3d3d3;">
</canvas>



</script>

<script>
var canvas = document.getElementById("myCanvas");
var ctx = canvas.getContext("2d");
ctx.font = "italic bold 20pt Arial";
var x_axis = 0
var y_axis = 0
var i = 1

{% for wishes in all_wish %}
 
ctx.save();

x_axis=x_axis+70
ctx.translate(40,100);
ctx.rotate(-Math.PI*2/(i));
ctx.fillText("{{wishes.wish_text}}",x_axis,y_axis);
x_axis=-(x_axis)
y_axis= y_axis+70
  	
ctx.restore();

{% endfor %}


</script>

<script>
window.onload = function() {
	
    var canvas = document.getElementById("myCanvas");
    var ctx = canvas.getContext("2d");
    var x_axis= 865
    var y_axis=50
    var temp=115
    {% for images in all_image %}
		var img = document.getElementById("img{{ forloop.counter }}"); 
		ctx.drawImage(img, x_axis+temp ,y_axis, 170, 180);
		temp=-temp
		y_axis=y_axis+115
  
    {% endfor %}
    
    
    var x_axis= 365
    var y_axis=50
    var temp=115
    {% for images_url in all_image_url %}
		var img = document.getElementById("imga{{ forloop.counter }}"); 
		ctx.drawImage(img, x_axis+temp ,y_axis, 170, 180);
		temp=-temp
		y_axis=y_axis+115
  
    {% endfor %}
};
</script>

</body>
</html>

Manish/home/templates/home/image_form.html
<!DOCTYPE html>
<html>
<head>
<title>Hunger Theka</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap&callback=initMap"></script>



<style>
            body {
                background: #aaa;
               
            }
            
            #myCanvas {
    			padding: 0;
    			margin: auto;
   				display: block;
    			width: 800px;
    			height: 600px;
    			position: absolute;
   				top: 0;
    			bottom: 0;
    			left: 0;
    			right: 0;
    			background:#bbb;
			}
        
</style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        
	<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:home'%}" style="font-size: 170%"">M K</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
           
           <ul class="nav navbar-nav navbar-left">
            
              <li class="">
		<a href="#">
		
			<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<i class="fa fa-facebook-square" style="font-size:24px;color:#c2c0c0"></i></span>
		</a>
		</li>
		
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-twitter-square' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-instagram' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		</li>
         
        </ul> 
           
            <ul class="nav navbar-nav navbar-right">
            
         
            <li class="">
		<a href="#">
		
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>&nbsp; 
			Doodle</a>
		</li>
            	<li class="">
		<a href="#">
			<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp;
			 Find Us</a>
		</li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 
			About Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp; 
			Contact Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; 
                        Developed by Sahil Kalra
                    </a>
                </li>
                

            </ul>
        </div>

    </div>
</nav>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
	{% include 'home/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
		
</form>


</form>

</body>
</html>

Manish/home/templates/home/image_url_form.html
<!DOCTYPE html>
<html>
<head>
<title>Hunger Theka</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap&callback=initMap"></script>



<style>
            body {
                background: #aaa;
               
            }
            
            #myCanvas {
    			padding: 0;
    			margin: auto;
   				display: block;
    			width: 800px;
    			height: 600px;
    			position: absolute;
   				top: 0;
    			bottom: 0;
    			left: 0;
    			right: 0;
    			background:#bbb;
			}
        
</style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        
	<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:home'%}" style="font-size: 170%"">M K</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
           
           <ul class="nav navbar-nav navbar-left">
            
              <li class="">
		<a href="#">
		
			<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<i class="fa fa-facebook-square" style="font-size:24px;color:#c2c0c0"></i></span>
		</a>
		</li>
		
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-twitter-square' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-instagram' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		</li>
         
        </ul> 
           
            <ul class="nav navbar-nav navbar-right">
            
         
            <li class="">
		<a href="#">
		
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>&nbsp; 
			Doodle</a>
		</li>
            	<li class="">
		<a href="#">
			<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp;
			 Find Us</a>
		</li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 
			About Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp; 
			Contact Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; 
                        Developed by Sahil Kalra
                    </a>
                </li>
                

            </ul>
        </div>

    </div>
</nav>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
	{% include 'home/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
		
</form>


</form>

</body>
</html>

Manish/home/templates/home/wish_form.html
<!DOCTYPE html>
<html>
<head>
<title>Hunger Theka</title>
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu-916DdpKAjTmJNIgngS6HL_kDIKU0aU&callback=myMap&callback=initMap"></script>



<style>
            body {
                background: #aaa;
               
            }
            
            #myCanvas {
    			padding: 0;
    			margin: auto;
   				display: block;
    			width: 800px;
    			height: 600px;
    			position: absolute;
   				top: 0;
    			bottom: 0;
    			left: 0;
    			right: 0;
    			background:#bbb;
			}
        
</style>

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        
	<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:home'%}" style="font-size: 170%"">M K</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
           
           <ul class="nav navbar-nav navbar-left">
            
              <li class="">
		<a href="#">
		
			<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<i class="fa fa-facebook-square" style="font-size:24px;color:#c2c0c0"></i></span>
		</a>
		</li>
		
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-twitter-square' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		<li class="">
		<a href="#">
		
			<span><i class='fa fa-instagram' style="font-size:24px;color:#c2c0c0""></i></span>
			
		</a>
		
		</li>
         
        </ul> 
           
            <ul class="nav navbar-nav navbar-right">
            
         
            <li class="">
		<a href="#">
		
			<span class="glyphicon glyphicon-cutlery" aria-hidden="true"></span>&nbsp; 
			Doodle</a>
		</li>
            	<li class="">
		<a href="#">
			<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>&nbsp;
			 Find Us</a>
		</li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 
			About Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp; 
			Contact Us
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; 
                        Developed by Sahil Kalra
                    </a>
                </li>
                

            </ul>
        </div>

    </div>
</nav>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
	{% include 'home/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Submit</button>
		</div>
		
</form>


</form>

</body>
</html>